config/routes.rb
Rails.application.routes.draw do
  resources :mers
  resources :colonies
  resources :polling_stations
  resources :sub_sectors
  resources :sectors
  resources :municipalities
  resources :departments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/polling_station.rb
class PollingStation < ApplicationRecord
  has_many :colonies
  has_many :mers
  belongs_to :sub_sector
end

app/controllers/polling_stations_controller.rb
class PollingStationsController < ApplicationController
  before_action :set_polling_station, only: [:show, :edit, :update, :destroy]

  # GET /polling_stations
  # GET /polling_stations.json
  def index
    @polling_stations = PollingStation.all
  end

  # GET /polling_stations/1
  # GET /polling_stations/1.json
  def show
  end

  # GET /polling_stations/new
  def new
    @polling_station = PollingStation.new
  end

  # GET /polling_stations/1/edit
  def edit
  end

  # POST /polling_stations
  # POST /polling_stations.json
  def create
    @polling_station = PollingStation.new(polling_station_params)

    respond_to do |format|
      if @polling_station.save
        format.html { redirect_to @polling_station, notice: 'Polling station was successfully created.' }
        format.json { render :show, status: :created, location: @polling_station }
      else
        format.html { render :new }
        format.json { render json: @polling_station.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /polling_stations/1
  # PATCH/PUT /polling_stations/1.json
  def update
    respond_to do |format|
      if @polling_station.update(polling_station_params)
        format.html { redirect_to @polling_station, notice: 'Polling station was successfully updated.' }
        format.json { render :show, status: :ok, location: @polling_station }
      else
        format.html { render :edit }
        format.json { render json: @polling_station.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /polling_stations/1
  # DELETE /polling_stations/1.json
  def destroy
    @polling_station.destroy
    respond_to do |format|
      format.html { redirect_to polling_stations_url, notice: 'Polling station was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_polling_station
      @polling_station = PollingStation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def polling_station_params
      params.require(:polling_station).permit(:sub_sector_id, :num_pollstat, :name)
    end
end

app/helpers/polling_stations_helper.rb
module PollingStationsHelper
end

app/views/polling_stations/_form.html.erb
<%= form_for(polling_station) do |f| %>
  <% if polling_station.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(polling_station.errors.count, "error") %> prohibited this polling_station from being saved:</h2>

      <ul>
      <% polling_station.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sub_sector_id %>
    <%= f.text_field :sub_sector_id %>
  </div>

  <div class="field">
    <%= f.label :num_pollstat %>
    <%= f.text_field :num_pollstat %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/polling_stations/edit.html.erb
<h1>Editing Polling Station</h1>

<%= render 'form', polling_station: @polling_station %>

<%= link_to 'Show', @polling_station %> |
<%= link_to 'Back', polling_stations_path %>

app/views/polling_stations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Polling Stations</h1>

<table>
  <thead>
    <tr>
      <th>Sub sector</th>
      <th>Num pollstat</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @polling_stations.each do |polling_station| %>
      <tr>
        <td><%= polling_station.sub_sector %></td>
        <td><%= polling_station.num_pollstat %></td>
        <td><%= polling_station.name %></td>
        <td><%= link_to 'Show', polling_station %></td>
        <td><%= link_to 'Edit', edit_polling_station_path(polling_station) %></td>
        <td><%= link_to 'Destroy', polling_station, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Polling Station', new_polling_station_path %>

app/views/polling_stations/new.html.erb
<h1>New Polling Station</h1>

<%= render 'form', polling_station: @polling_station %>

<%= link_to 'Back', polling_stations_path %>

app/views/polling_stations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sub sector:</strong>
  <%= @polling_station.sub_sector %>
</p>

<p>
  <strong>Num pollstat:</strong>
  <%= @polling_station.num_pollstat %>
</p>

<p>
  <strong>Name:</strong>
  <%= @polling_station.name %>
</p>

<%= link_to 'Edit', edit_polling_station_path(@polling_station) %> |
<%= link_to 'Back', polling_stations_path %>