config/routes.rb
Rails.application.routes.draw do
  resources :mers
  resources :colonies
  resources :polling_stations
  resources :sub_sectors
  resources :sectors
  resources :municipalities
  resources :departments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/municipality.rb
class Municipality < ApplicationRecord
  has_many :sectors
  belongs_to :department
end

app/controllers/municipalities_controller.rb
class MunicipalitiesController < ApplicationController
  before_action :set_municipality, only: [:show, :edit, :update, :destroy]

  # GET /municipalities
  # GET /municipalities.json
  def index
    @municipalities = Municipality.all
  end

  # GET /municipalities/1
  # GET /municipalities/1.json
  def show
  end

  # GET /municipalities/new
  def new
    @municipality = Municipality.new
  end

  # GET /municipalities/1/edit
  def edit
  end

  # POST /municipalities
  # POST /municipalities.json
  def create
    @municipality = Municipality.new(municipality_params)

    respond_to do |format|
      if @municipality.save
        format.html { redirect_to @municipality, notice: 'Municipality was successfully created.' }
        format.json { render :show, status: :created, location: @municipality }
      else
        format.html { render :new }
        format.json { render json: @municipality.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /municipalities/1
  # PATCH/PUT /municipalities/1.json
  def update
    respond_to do |format|
      if @municipality.update(municipality_params)
        format.html { redirect_to @municipality, notice: 'Municipality was successfully updated.' }
        format.json { render :show, status: :ok, location: @municipality }
      else
        format.html { render :edit }
        format.json { render json: @municipality.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /municipalities/1
  # DELETE /municipalities/1.json
  def destroy
    @municipality.destroy
    respond_to do |format|
      format.html { redirect_to municipalities_path(:department => @municipality.department), notice: 'Municipality was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_municipality
      @municipality = Municipality.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def municipality_params
      params.require(:municipality).permit(:department_id, :num_minicip, :name)
    end
end

app/helpers/municipalities_helper.rb
module MunicipalitiesHelper
end

app/views/municipalities/_form.html.erb
<%= form_for(municipality) do |f| %>
  <% if municipality.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(municipality.errors.count, "error") %> prohibited this municipality from being saved:</h2>

      <ul>
      <% municipality.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :department_id, :value => params[:intern_department], :hidden => true %>
  </div>

  <div class="field">
    <%= f.label :"Código" %>
    <%= f.text_field :num_minicip %>
  </div>

  <div class="field">
    <%= f.label :"Nombre" %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/municipalities/edit.html.erb
<h1>Editing Municipality</h1>

<%= render 'form', municipality: @municipality %>

<%= link_to 'Show', @municipality %> |
<%= link_to 'Atras', municipalities_path(:department => @municipality.department) %>

app/views/municipalities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Municipios de <%= Department.find(params[:department]).name %></h1>

<table>
  <thead>
    <tr>
      <th>Código</th>
      <th>Municipio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @municipalities.where(department: params[:department]).each do |municipality| %>
    <!--% @municipalities.each do |municipality| %-->
      <tr>
        <td><%= municipality.num_minicip %></td>
        <td><%= municipality.name %></td>
        <td><%= link_to 'Mostrar', municipality %></td>
        <td><%= link_to 'Sector', sectors_path(:municipality => municipality) %></td>
        <td><%= link_to 'Modificar', edit_municipality_path(municipality, :intern_department => params[:department]) %></td>
        <td><%= link_to 'Eliminar', municipality, method: :delete, data: { confirm: 'Esta Seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Agregar Municipio', new_municipality_path(:intern_department => params[:department]) %>
<%= link_to 'Atras', departments_path %>

app/views/municipalities/new.html.erb
<h1>New Municipality</h1>

<%= render 'form', municipality: @municipality %>

<%= link_to 'Atras', municipalities_path(:deparment => params[:intern_department]) %>

app/views/municipalities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Departamento:</strong>
  <%= @municipality.department.name %>
</p>

<p>
  <strong>Código:</strong>
  <%= @municipality.num_minicip %>
</p>

<p>
  <strong>Municipio:</strong>
  <%= @municipality.name %>
</p>

<%= link_to 'Modificar', edit_municipality_path(@municipality, :department => @municipality.department) %> |
<%= link_to 'Atras', municipalities_path(:department => @municipality.department) %>